#!/usr/bin/env bash
# Usage: ndenv completions <command> [arg1 arg2...]

set -e
[ -n "$NDENV_DEBUG" ] && set -x

COMMAND="$1"
if [ -z "$COMMAND" ]; then
  ndenv-help --usage completions >&2
  exit 1
fi

COMMAND_PATH="$(command -v "ndenv-$COMMAND" || command -v "ndenv-sh-$COMMAND")"
if grep -i "^\([#%]\|--\|//\) provide ndenv completions" "$COMMAND_PATH" >/dev/null; then
  shift
  exec "$COMMAND_PATH" --complete "$@"
fi
