#!/usr/bin/env bash
# Summary: Show the current Node version and its origin
#
# Shows the currently selected Node version and how it was
# selected. To obtain only the version string, use `ndenv
# version-name'.

set -e
[ -n "$NDENV_DEBUG" ] && set -x

echo "$(ndenv-version-name) (set by $(ndenv-version-origin))"
