#!/usr/bin/env bash
# Summary: Explain how the current Node version is set
set -e
[ -n "$NDENV_DEBUG" ] && set -x

if [ -n "$NDENV_VERSION" ]; then
  echo "NDENV_VERSION environment variable"
else
  ndenv-version-file
fi
